CREATE TABLE Users (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Age INT,
    Email VARCHAR(150) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Roles (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    RoleName VARCHAR(100) NOT NULL
);

CREATE TABLE Posts (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Category VARCHAR(100),
    Body TEXT NOT NULL,
    Likes INT DEFAULT 0,
    Share INT DEFAULT 0,
    User_Id INT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_Id) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE User_Role (
    User_Id INT,
    Role_Id INT,
    PRIMARY KEY (User_Id, Role_Id),
    FOREIGN KEY (User_Id) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (Role_Id) REFERENCES Roles(Id) ON DELETE CASCADE
);
